const SPOTIFY_API_BASE = 'https://api.spotify.com/v1';

export const createPlaylist = async (playlistName: string, isPublic: boolean, accessToken: string) => {
    try {
        const response = await fetch(`${SPOTIFY_API_BASE}/me/playlists`, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${accessToken}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                name: playlistName,
                description: 'Generated by Recommendify',
                public: isPublic
            })
        });

        if (!response.ok) {
            throw new Error('Failed to create playlist.');
        }

        return await response.json();
    } catch (error) {
        console.error('Error creating playlist:', error);
        throw error;
    }
};

export const addTracksToPlaylist = async (playlistId: string, trackUris: string[], accessToken: string) => {
    try {
        const response = await fetch(`${SPOTIFY_API_BASE}/playlists/${playlistId}/tracks`, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${accessToken}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({uris: trackUris})
        });

        if (!response.ok) {
            throw new Error('Failed to add tracks to playlist.');
        }

        return await response.json();
    } catch (error) {
        console.error('Error adding tracks to playlist:', error);
        throw error;
    }
};
